using MediatR;
namespace CatalogService.Application.Features.IntegrationEventHandlers.ProductVariantPriceSnapshot.DeleteProductVariantPriceSnapshot;

public sealed record DeleteProductVariantPriceSnapshotCommand(Guid ProductVariantId) : IRequest;