syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

package catalog.v1;

option csharp_namespace = "CatalogService.Api.Grpc.V1.Protos";

service CatalogService {
	rpc CreateProduct(CreateProductRequest) returns (google.protobuf.Empty);
    rpc UpdateProductInfo(UpdateProductInfoRequest) returns (google.protobuf.Empty);

    rpc PublishProduct(PublishProductRequest) returns (google.protobuf.Empty);
    rpc UnpublishProduct(UnpublishProductRequest) returns (google.protobuf.Empty);

    rpc LockProduct(LockProductRequest) returns (google.protobuf.Empty);
    rpc UnlockProduct(UnlockProductRequest) returns (google.protobuf.Empty);

    rpc ArchiveProduct(ArchiveProductRequest) returns (google.protobuf.Empty);
    rpc RestoreProduct(RestoreProductRequest) returns (google.protobuf.Empty);

    rpc DeleteProduct(DeleteProductRequest) returns (google.protobuf.Empty);

    rpc ReplaceProductAttributes(ReplaceProductAttributesRequest) returns (google.protobuf.Empty);
    rpc ReplaceProductTags(ReplaceProductTagsRequest) returns (google.protobuf.Empty);
}

message CreateProductRequest {
    string vendor_id = 1;
    string category_id = 2;
    string brand_id = 3;
    string name = 4; 
    string slug = 5;
    string description = 6;
    string short_description = 7;
    string seo_title = 8;
    string seo_description = 9;
    string seo_keywords = 10;
}

message UpdateProductInfoRequest {
    string product_id = 1;
    string vendor_id = 2;
    string name = 3;
    string slug = 4;
    string description = 5;
    string short_description = 6;
    string category_id = 7;
    string brand_id = 8;
    string seo_title = 9;
    string seo_description = 10;
    string seo_keywords = 11;
}

message PublishProductRequest {
    string product_id = 1;
    string vendor_id = 2;
}

message UnpublishProductRequest {
    string product_id = 1;
    string vendor_id = 2;
}

message LockProductRequest {
    string product_id = 1;
}

message UnlockProductRequest {
    string product_id = 1;
}

message ArchiveProductRequest {
    string product_id = 1;
    string vendor_id = 2;
}

message RestoreProductRequest {
    string product_id = 1;
    string vendor_id = 2;
}

message DeleteProductRequest {
    string product_id = 1;
    string vendor_id = 2;
}

message ReplaceProductAttributesRequest {
    string vendor_id = 1;
    string product_id = 2;
    map<string, string> attributes = 3;
}

message ReplaceProductTagsRequest {
    string vendor_id = 1;
    string product_id = 2;
    repeated string tags = 3;
}