syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

package catalog.v1;

option csharp_namespace = "CatalogService.Api.Grpc.V1.Protos";

service CatalogService {
	rpc CreateProductCard(CreateProductCardRequest) returns (google.protobuf.Empty);
    rpc UpdateProductCardInfo(UpdateProductCardInfoRequest) returns (google.protobuf.Empty);

    rpc PublishProductCard(PublishProductCardRequest) returns (google.protobuf.Empty);
    rpc ArchiveProductCard(ArchiveProductCardRequest) returns (google.protobuf.Empty);

    rpc ReplaceProductCardAttributes(ReplaceProductCardAttributesRequest) returns (google.protobuf.Empty);
    rpc ReplaceProductCardTags(ReplaceProductCardTagsRequest) returns (google.protobuf.Empty);

    rpc AddProductCardImage(AddProductCardImageRequest) returns (google.protobuf.Empty);
    rpc RemoveProductCardImage(RemoveProductCardImageRequest) returns (google.protobuf.Empty);
    rpc ChangeProductCardImageOrder(ChangeProductCardImageOrderRequest) returns (google.protobuf.Empty);
    rpc SetMainProductCardImage(SetMainProductCardImageRequest) returns (google.protobuf.Empty);
    rpc UpdateProductCardImageAlt(UpdateProductCardImageAltRequest) returns (google.protobuf.Empty);

    rpc GetProductCardById(GetProductCardByIdRequest) returns (GetProductCardByIdResponse);
}

message ProductCardDto {
    string id = 1;
    string name = 2;
    string slug = 3;
    string description = 4;
    string short_description = 5;
    double rating_avg = 6;
    int32 rating_count = 7;
    string default_product_id = 8;
    int32 product_count = 9;
    int64 price_minor_amount = 10;
    int64 old_price_minor_amount = 11;
    StockStatus stock_status = 12;
    string category_id = 13;
    string category_name = 15;
    string category_slug = 16;
    string vendor_id = 17;
    string brand = 18;
    ProductCardStatus product_card_status = 19;
    SeoMetadataDto seo_metadata = 20;
    map<string, string> attributes = 21;
    repeated string tags = 22;
    repeated ProductCardImageDto images = 23;
}

message SeoMetadataDto {
    string title = 1;
    string description = 2;
    string keywords = 3;
}

message ProductCardImageDto {
    string url = 1;
    string alt = 2;
    bool is_main = 3;
    int32 sort_order = 4;
}

enum StockStatus {
    IN_STOCK = 0;
    OUT_OF_STOCK = 1;
    PREORDER = 2;
    BLOCKED = 3;
}

enum ProductCardStatus {
    DRAFT = 0;
    PUBLISHED = 1;
    ARCHIVED = 2;
}

message CreateProductCardRequest {
    string vendor_id = 1;
    string category_id = 2;
    string name = 3; 
    string slug = 4;
    string description = 5;
    string short_description = 6;
    string brand = 7;
    string seo_title = 8;
    string seo_description = 9;
    string seo_keywords = 10;
    map<string, string> attributes = 11;
    repeated string tags = 12;
}

message UpdateProductCardInfoRequest {
    string product_card_id = 1;
    string vendor_id = 2;
    string name = 3;
    string description = 4;
    string short_description = 5;
    string category_id = 6;
    string brand = 7;
    string seo_title = 8;
    string seo_description = 9;
    string seo_keywords = 10;
}

message PublishProductCardRequest {
    string product_card_id = 1;
    string vendor_id = 2;
}

message ArchiveProductCardRequest {
    string product_card_id = 1;
    string vendor_id = 2;
}

message ReplaceProductCardAttributesRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    map<string, string> attributes = 3;
}

message ReplaceProductCardTagsRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    repeated string tags = 3;
}

message AddProductCardImageRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    string url = 3;
    string alt = 4;
    bool is_main = 5;
    int32 sort_order = 6;
}

message RemoveProductCardImageRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    string url = 3;
}

message ChangeProductCardImageOrderRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    string url = 3;
    int32 new_sort_order = 4;
}

message SetMainProductCardImageRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    string url = 3;
}

message UpdateProductCardImageAltRequest {
    string vendor_id = 1;
    string product_card_id = 2;
    string url = 3;
    string new_alt = 4;
}

message GetProductCardByIdRequest {
    string product_card_id = 1;
    string currncy_code = 2;
}

message GetProductCardByIdResponse {
    ProductCardDto product_card = 1;
}