using MediatR;

namespace CatalogService.Application.Features.IntegrationEventHandlers.ProductVariantSnapshot.DeleteProductVariantSnapshot;

public sealed record DeleteProductVariantSnapshotCommand(Guid ProductVariantId) : IRequest;